spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql